const styles = {
  card: {
    maxWidth: 900,
    margin: "3rem auto",
    padding: 32,
    borderRadius: 16,
    background: "#fff",
    boxShadow: "0 4px 24px 0 rgba(0,0,0,0.08)",
    border: "1px solid #e5e7eb",
    transition: "box-shadow 0.2s",
  },
  title: {
    fontSize: 24,
    fontWeight: 700,
    marginBottom: 28,
    letterSpacing: -1,
    color: "#222",
    textAlign: "left" as const,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
    background: "#fff",
    borderRadius: 12,
    overflow: "hidden",
    boxShadow: "0 1px 4px 0 rgba(0,0,0,0.03)",
    fontFamily: "inherit",
  },
  th: {
    background: "#f3f6fa",
    color: "#222",
    fontWeight: 600,
    fontSize: 16,
    padding: "14px 10px",
    borderBottom: "2px solid #e5e7eb",
    textAlign: "center" as const,
    letterSpacing: -0.5,
    userSelect: "none" as const,
  },
  td: {
    padding: "12px 10px",
    borderBottom: "1px solid #f1f1f1",
    fontSize: 15,
    textAlign: "center" as const,
    color: "#333",
    background: "#fff",
    transition: "background 0.2s",
    verticalAlign: "middle" as const,
    wordBreak: "break-all" as const,
  },
  trHover: {
    background: "#f9fbfd",
    transition: "background 0.2s",
  },
  loading: {
    textAlign: "center" as const,
    color: "#3b82f6",
    fontSize: 18,
    padding: 40,
  },
  nickname: {
    color: "#2563eb",
    cursor: "pointer",
    textDecoration: "underline",
    fontWeight: 500,
    transition: "color 0.2s",
  },
  nicknameInput: {
    width: 120,
    fontSize: 15,
    padding: "4px 8px",
    border: "1px solid #bcd0ee",
    borderRadius: 6,
    outline: "none",
    background: "#f8fafc",
    color: "#222",
  },
  deleteBtn: {
    color: "#ef4444",
    background: "none",
    border: "none",
    fontSize: 18,
    cursor: "pointer",
    marginRight: 8,
  },
};

export default styles;