const styles = {
  card: {
    maxWidth: 400,
    width: "95vw",
    margin: "3rem auto",
    padding: "40px 28px 32px 28px",
    borderRadius: 18,
    background: "#fff",
    boxShadow: "0 6px 32px 0 rgba(0,0,0,0.10)",
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    position: "relative" as const,
  },
  title: {
    fontSize: 26,
    fontWeight: 800,
    marginBottom: 28,
    letterSpacing: -1,
    color: "#222",
    textAlign: "center" as const,
  },
  radioGroup: {
    display: "flex",
    justifyContent: "center",
    gap: 32,
    marginBottom: 22,
    width: "100%",
  },
  radioLabel: {
    fontSize: 17,
    fontWeight: 600,
    color: "#444",
    display: "flex",
    alignItems: "center",
    gap: 7,
    cursor: "pointer",
    userSelect: "none" as const,
  },
  select: {
    width: "100%",
    padding: "12px 14px",
    borderRadius: 9,
    border: "1.5px solid #d0d7de",
    fontSize: 16,
    marginBottom: 14,
    background: "#f8fafc",
    outline: "none",
    fontWeight: 500,
  },
  input: {
    width: "100%",
    padding: "12px 14px",
    borderRadius: 9,
    border: "1.5px solid #d0d7de",
    fontSize: 16,
    marginBottom: 14,
    background: "#f8fafc",
    outline: "none",
    transition: "border 0.2s",
    fontWeight: 500,
  },
  inputError: {
    border: "1.5px solid #e74c3c",
    background: "#fff6f6",
  },
  error: {
    color: "#e74c3c",
    fontSize: 13,
    margin: "-8px 0 8px 2px",
    minHeight: 18,
    width: "100%",
    textAlign: "left" as const,
  },
  button: {
    width: "100%",
    padding: "14px 0",
    borderRadius: 9,
    border: "none",
    background: "#2563eb",
    color: "#fff",
    fontWeight: 800,
    fontSize: 17,
    cursor: "pointer",
    marginTop: 10,
    transition: "background 0.2s",
    boxShadow: "0 2px 8px 0 rgba(37,99,235,0.08)",
  },
  buttonDisabled: {
    background: "#b6c3d1",
    cursor: "not-allowed",
  },
  message: {
    marginTop: 20,
    fontSize: 15,
    fontWeight: 600,
    textAlign: "center" as const,
  },
  companySearchWrap: {
    width: "100%",
    marginBottom: 14,
    marginTop: 18,
    position: "relative" as const,
    display: "flex",
    gap: 8,
    alignItems: "center",
  },
  companySearchBtn: {
    padding: "0 18px",
    borderRadius: 9,
    border: "1.5px solid #2563eb",
    background: "#2563eb",
    color: "#fff",
    fontWeight: 700,
    fontSize: 16,
    cursor: "pointer",
    minWidth: 62,
    height: 48,
    transition: "background 0.2s",
  },
  companyDropdown: {
    position: "absolute" as const,
    top: 50,
    left: 0,
    right: 0,
    background: "#fff",
    border: "1.5px solid #d0d7de",
    borderRadius: 9,
    maxHeight: 200,
    overflowY: "auto" as const,
    boxShadow: "0 2px 12px 0 rgba(0,0,0,0.10)",
    zIndex: 20,
  },
  companyDropdownItem: {
    padding: "12px 18px",
    cursor: "pointer",
    borderBottom: "1px solid #f1f1f1",
    background: "#fff",
    transition: "background 0.15s",
  },
  companyDropdownItemActive: {
    background: "#e0e7ff",
  },
  companyDropdownName: {
    fontWeight: 600,
    fontSize: 15,
  },
  companyDropdownCode: {
    fontSize: 13,
    color: "#888",
    marginTop: 2,
  },
  searchLoading: {
    position: "absolute" as const,
    top: 50,
    left: 0,
    color: "#888",
    fontSize: 14,
    background: "#fff",
    width: "100%",
    textAlign: "center" as const,
    borderRadius: 9,
    padding: "8px 0",
    zIndex: 21,
    border: "1.5px solid #d0d7de",
    boxShadow: "0 2px 12px 0 rgba(0,0,0,0.10)",
  },
};

export default styles;